server {
    listen 80;
    server_name localhost;

    # Ruta para servir los archivos del juego Mario RPG
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # Ruta especial para exponer el estado interno de Nginx (conexiones activas)
    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;           # Permite llamadas locales
        allow 172.16.0.0/12;        # Permite llamadas desde la red de Docker
        # deny all;                 # Podés descomentar esto para bloquear cualquier otro origen externo
    }
}